package org.iesalandalus.programacion.alquilervehiculos.vista.texto;

public enum Accion {
SALIR, 
INSETAR_CLIENTES, 
INSERTAR_VEHICULO,
INSERTAR_ALQUILER,
BUSCAR_CLIENTE,
BUSCAR_VEHICULO,
BUSCAR_ALQUILER,
MODIFICAR_CLIENTE,
DEVOLVER_ALQUILER_VEHICULO,
DEVOLVER_ALQUILER_CLIENTE,
BORRAR_CLIENTE,
BORRAR_VEHICULO,
BORRAR_ALQUILER,
LISTAR_CLIENTE, 
LISTAR_VEHICULO,
LISTAR_ALQUILERES,
LISTAR_ALQUILERES_CLIENTES,
LISTAR_ALQUILERES_VEHICULO,
MOSTRAR_ESTADITICAS_MESUALES;
}
